# Load base image and set working directory
FROM node:21
WORKDIR /app

# Install project dependencies
COPY package*.json ./
RUN npm install

# Expose the port that the application will run on
EXPOSE 80

# Start the application with hot-reload
CMD npm run dev -- --host 0.0.0.0 --port 80 --logLevel info
