platform: Prediction platforms {
  shape: cloud
  style.multiple: true
}

themis: Themis {
  Fetch: {
    shape: rectangle
  }
  Postgres: {
    shape: cylinder
  }
  Serve: {
    shape: rectangle
    style.multiple: true
  }
}

Client: {
  shape: person
  style.multiple: true
}

direction: down

platform -> themis.Fetch
platform -> themis.Fetch: Platform API
platform -> themis.Fetch

themis.Fetch -> themis.Postgres: Daily refresh
themis.Postgres <-> themis.Serve: Query & cache

themis.Serve -> Client: Client queries
